version: '3'
services:
  # Redis server for websocket use
  redis:
    container_name: redis
    network_mode: host
    restart: always
    image: redis:latest

  # Django backend container with WS logic (Django Channels)
  django:
    image: maes95/outsider-backend:1.0.1
    network_mode: host
    depends_on:
      - redis

  # Main container / Vue frontend
  vue_frontend:
    restart: always
    image: maes95/outsider-front:1.0.11
    network_mode: host
