# Generated by Django 4.2.5 on 2023-12-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RoomModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre de la sala",
                        max_length=256,
                        unique=True,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "current_connections",
                    models.JSONField(
                        blank=True,
                        default=None,
                        null=True,
                        verbose_name="Lista de conexiones actuales",
                    ),
                ),
            ],
            options={
                "verbose_name": "Room",
                "verbose_name_plural": "Rooms",
            },
        ),
        migrations.CreateModel(
            name="WordsListModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre de la lista",
                        max_length=256,
                        unique=True,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "word_list",
                    models.JSONField(
                        help_text="Donde 'a' es la pista para los jugadores y 'b' es la pista para los outsiders",
                        verbose_name="Lista de palabras",
                    ),
                ),
            ],
            options={
                "verbose_name": "Word list",
                "verbose_name_plural": "Word lists",
            },
        ),
    ]
