# Generated by Django 4.2.5 on 2024-03-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RoomModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre de la sala",
                        max_length=256,
                        unique=True,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "current_connections",
                    models.JSONField(
                        blank=True,
                        default=list,
                        null=True,
                        verbose_name="Lista de conexiones actuales",
                    ),
                ),
                (
                    "number_outsiders",
                    models.IntegerField(
                        default=1,
                        help_text="Número actual de outsiders en la partida",
                        verbose_name="Outsiders",
                    ),
                ),
                (
                    "repeated_words",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Lista de palabras usadas en la partida",
                        null=True,
                        verbose_name="Palabras repetidas",
                    ),
                ),
                (
                    "started_game",
                    models.BooleanField(
                        default=False,
                        help_text="Indica si la partida ha empezado",
                        verbose_name="Partida en transcurso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Room",
                "verbose_name_plural": "Rooms",
            },
        ),
        migrations.CreateModel(
            name="WordsListModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre de la lista",
                        max_length=256,
                        unique=True,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "word_list",
                    models.JSONField(
                        help_text="Donde 'a' es la pista para los jugadores y 'b' es la pista para los outsiders",
                        verbose_name="Lista de palabras",
                    ),
                ),
            ],
            options={
                "verbose_name": "Word list",
                "verbose_name_plural": "Word lists",
            },
        ),
    ]
