# Generated by Django 4.2.5 on 2024-01-16 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logic", "0002_alter_roommodel_current_connections"),
    ]

    operations = [
        migrations.AddField(
            model_name="roommodel",
            name="started_game",
            field=models.BooleanField(
                default=False,
                help_text="Indica si la partida ha empezado",
                verbose_name="Partida en transcurso",
            ),
        ),
    ]
