# Generated by Django 4.2.5 on 2024-01-25 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logic", "0003_roommodel_started_game"),
    ]

    operations = [
        migrations.AddField(
            model_name="roommodel",
            name="number_outsiders",
            field=models.IntegerField(
                default=1,
                help_text="Número actual de outsiders en la partida",
                verbose_name="Outsiders",
            ),
        ),
        migrations.AddField(
            model_name="roommodel",
            name="repeated_words",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Lista de palabras usadas en la partida",
                null=True,
                verbose_name="Palabras repetidas",
            ),
        ),
    ]
